# See http://www.appveyor.com/docs/appveyor-yml for many more options
environment:
  NugetApiKey:
    secure: gma/ej3eXmpNjFaZ7n9CEqsSRfwFL9Ol9eKWzEALN7P697t8cQKr/OlaZ3y9MXhL    

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated (readme|doc).*|update (readme|doc).*s/

install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module PsScriptAnalyzer -Force
  - ps: Install-Module -Name AzureRM.CognitiveServices -Force
  - ps: Install-Module -Name AzureRM.Profile -Force
  - ps: Install-Module -Name AzureRM.CognitiveServices.Netcore -Force
  - ps: Install-Module -Name AzureRM.Profile.Netcore -Force

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1 -task 'Deploy'
